translations = {
    "en": {
        "title": "Transient Response of Capacitor Energization Current",
        "voltage": "3𝝋 Voltage [kV]",
        "frequency": "Frequency [Hz]",
        "short_circuit_current": "Short-Circuit Current at the Bus [kA]",
        "number_of_banks": "Number of Banks",
        "safety_factor": "Safety Factor",
        "energize_bank": "#### Bank to be energized $(\\#0)$",
        "already_energized_banks": "#### Banks already energized $(\\#1$ to $\\#n)$",
        "results": "#### Results",
        "nominal_current": "Nominal current of the bank $I_{\\rm rated}=$",
        "for_single_bank": "##### For single bank",
        "peak_current_energization": "Peak energization current $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Oscillation Frequency = ",
        "for_bank_with_others_energized": "##### For bank with other banks energized",
        "conclusion": "#### Conclusion",
        "conclusion_text": "Typical amplitudes of inrush currents for back-to-back capacitor bank energization are several ${\\rm kA}$ with frequencies from $2{\\rm~kHz}$ to $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Adequate reactor, as $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "not_adequate_reactor": "Reactor NOT adequate, as OR $\\dfrac{I_{\\rm inrush}}{I_{\\rm nominal}} = $",
        "bibliography": "#### Bibliography",
        "latex_report": "Generate PDF",
        "development": "#### Development",
        "instantaneous": "Instantaneous",
        "envelope": "Envelope",
        "reference_60hz": "Reference 60 Hz",
        "current_label": "Current:",
        "time_label": "Time [ms]",
        "current_axis_label": "Current [pu]",
        "voltage_axis_label": "Voltage [pu]",
        "use_xelatex_compiler": "use the xelatex compiler",
        "or": "or",
    },

    "pt": {
        "title": "Resposta transitória da corrente de energização de capacitores",
        "voltage": "Tensão 3𝝋 [kV]",
        "frequency": "Frequência [Hz]",
        "short_circuit_current": "Corrente de curto-circuito na barra [kA]",
        "number_of_banks": "Número de Bancos",
        "safety_factor": "Fator de Segurança",
        "energize_bank": "#### Banco a ser energizado $(\\#0)$",
        "already_energized_banks": "#### Bancos já energizados $(\\#1$ ao $\\#n)$",
        "results": "#### Resultados",
        "nominal_current": "Corrente nominal do banco $I_{\\rm rated}=$",
        "for_single_bank": "##### Para banco único",
        "peak_current_energization": "Corrente de pico na energização $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Frequência de Oscilação = ",
        "for_bank_with_others_energized": "##### Para banco com os demais bancos energizados",
        "conclusion": "#### Conclusão",
        "conclusion_text": "As amplitudes típicas das correntes de *inrush* para energização *back-to-back* de bancos de capacitores são de vários ${\\rm kA}$ com frequências de $2{\\rm~kHz}$ a $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Reator adequado, pois $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "not_adequate_reactor": "Reator NÃO adequado, pois OU $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "bibliography": "#### Bibliografia",
        "latex_report": "Gerar PDF",
        "development": "#### Desenvolvimento",
        "instantaneous": "Instantânea",
        "envelope": "Envelope",
        "reference_60hz": "Referência 60 Hz",
        "current_label": "Corrente:",
        "time_label": "Tempo [ms]",
        "current_axis_label": "Corrente [pu]",
        "voltage_axis_label": "Tensão [pu]",
        "use_xelatex_compiler": "usar o compilador xelatex",
        "or": "ou",
    },

    "zh": {
        "title": "电容器投切电流的瞬态响应",
        "voltage": "三相电压 [kV]",
        "frequency": "频率 [Hz]",
        "short_circuit_current": "母线短路电流 [kA]",
        "number_of_banks": "电容器组数量",
        "safety_factor": "安全系数",
        "energize_bank": "#### 待投入的电容器组 $(\\#0)$",
        "already_energized_banks": "#### 已投入的电容器组 $(\\#1$ 到 $\\#n)$",
        "results": "#### 结果",
        "nominal_current": "电容器组额定电流 $I_{\\rm rated}=$",
        "for_single_bank": "##### 单个电容器组",
        "peak_current_energization": "投切峰值电流 $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "振荡频率 = ",
        "for_bank_with_others_energized": "##### 已投入的其他电容器组",
        "conclusion": "#### 结论",
        "conclusion_text": "背靠背投切电容器组的典型浪涌电流幅值为数 ${\\rm kA}$，频率为 $2{\\rm~kHz}$ 至 $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "电抗器合适，因为 $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "not_adequate_reactor": "电抗器不合适，因为 或 $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "bibliography": "#### 参考文献",
        "latex_report": "生成 PDF",
        "development": "#### 发展",
        "instantaneous": "瞬时",
        "envelope": "包络",
        "reference_60hz": "参考 60 Hz",
        "current_label": "电流:",
        "time_label": "时间 [ms]",
        "current_axis_label": "电流 [pu]",
        "voltage_axis_label": "电压 [pu]",
        "use_xelatex_compiler": "使用 xelatex 编译器",
        "or": "或",
    },

    "es": {
        "title": "Respuesta transitoria de la corriente de energización de condensadores",
        "voltage": "Voltaje 3𝝋 [kV]",
        "frequency": "Frecuencia [Hz]",
        "short_circuit_current": "Corriente de cortocircuito en la barra [kA]",
        "number_of_banks": "Número de Bancos",
        "safety_factor": "Factor de Seguridad",
        "energize_bank": "#### Banco a energizar $(\\#0)$",
        "already_energized_banks": "#### Bancos ya energizados $(\\#1$ a $\\#n)$",
        "results": "#### Resultados",
        "nominal_current": "Corriente nominal del banco $I_{\\rm rated}=$",
        "for_single_bank": "##### Para banco único",
        "peak_current_energization": "Corriente de pico en la energización $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Frecuencia de Oscilación = ",
        "for_bank_with_others_energized": "##### Para banco con los demás bancos energizados",
        "conclusion": "#### Conclusión",
        "conclusion_text": "Las amplitudes típicas de las corrientes de irrupción para la energización back-to-back de bancos de capacitores son de varios ${\\rm kA}$ con frecuencias de $2{\\rm~kHz}$ a $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Reactor adecuado, ya que $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "not_adequate_reactor": "Reactor NO adecuado, ya que O $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "bibliography": "#### Bibliografía",
        "latex_report": "Generar PDF",
        "development": "#### Desarrollo",
        "instantaneous": "Instantánea",
        "envelope": "Envolvente",
        "reference_60hz": "Referencia 60 Hz",
        "current_label": "Corriente:",
        "time_label": "Tiempo [ms]",
        "current_axis_label": "Corriente [pu]",
        "voltage_axis_label": "Voltaje [pu]",
        "use_xelatex_compiler": "usar el compilador xelatex",
        "or": "o",
    },

    "fr": {
        "title": "Réponse transitoire du courant d'enclenchement des condensateurs",
        "voltage": "Tension 3𝝋 [kV]",
        "frequency": "Fréquence [Hz]",
        "short_circuit_current": "Courant de court-circuit au bus [kA]",
        "number_of_banks": "Nombre de Bancs",
        "safety_factor": "Facteur de Sécurité",
        "energize_bank": "#### Banc à enclencher $(\\#0)$",
        "already_energized_banks": "#### Bancs déjà enclenchés $(\\#1$ à $\\#n)$",
        "results": "#### Résultats",
        "nominal_current": "Courant nominal du banc $I_{\\rm rated}=$",
        "for_single_bank": "##### Pour banc unique",
        "peak_current_energization": "Courant de crête lors de l’enclenchement $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Fréquence d’oscillation = ",
        "for_bank_with_others_energized": "##### Pour banc avec autres bancs enclenchés",
        "conclusion": "#### Conclusion",
        "conclusion_text": "Les courants d'appel typiques pour l’enclenchement back-to-back des bancs de condensateurs atteignent plusieurs ${\\rm kA}$ avec des fréquences de $2{\\rm~kHz}$ à $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Réacteur adéquat, car $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "not_adequate_reactor": "Réacteur NON adéquat, car OU $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "bibliography": "#### Bibliographie",
        "latex_report": "Générer PDF",
        "development": "#### Développement",
        "instantaneous": "Instantanée",
        "envelope": "Enveloppe",
        "reference_60hz": "Référence 60 Hz",
        "current_label": "Courant:",
        "time_label": "Temps [ms]",
        "current_axis_label": "Courant [pu]",
        "voltage_axis_label": "Tension [pu]",
        "use_xelatex_compiler": "utiliser le compilateur xelatex",
        "or": "ou",
    },

    "de": {
        "title": "Übergangsantwort des Einschaltstroms von Kondensatoren",
        "voltage": "Spannung 3𝝋 [kV]",
        "frequency": "Frequenz [Hz]",
        "short_circuit_current": "Kurzschlussstrom an der Sammelschiene [kA]",
        "number_of_banks": "Anzahl der Bänke",
        "safety_factor": "Sicherheitsfaktor",
        "energize_bank": "#### Zu schaltender Bank $(\\#0)$",
        "already_energized_banks": "#### Bereits zugeschaltete Bänke $(\\#1$ bis $\\#n)$",
        "results": "#### Ergebnisse",
        "nominal_current": "Nennstrom des Bankes $I_{\\rm rated}=$",
        "for_single_bank": "##### Für einzelnen Bank",
        "peak_current_energization": "Spitzenstrom beim Einschalten $I_{\\rm{inrush}}=$",
        "oscillation_frequency": "Oszillationsfrequenz = ",
        "for_bank_with_others_energized": "##### Für Bank mit anderen zugeschalteten Bänken",
        "conclusion": "#### Schlussfolgerung",
        "conclusion_text": "Typische Einschaltstromamplituden bei Back-to-Back-Schaltung von Kondensatorbänken liegen bei mehreren ${\\rm kA}$ und Frequenzen von $2{\\rm~kHz}$ bis $5{\\rm~kHz}$ [$^{[1]}$](https://ieeexplore.ieee.org/document/7035261).",
        "adequate_reactor": "Reaktor geeignet, da $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "not_adequate_reactor": "Reaktor NICHT geeignet, da ODER $\\dfrac{I_{\\rm inrush}}{I_{\\rm rated}} = $",
        "bibliography": "#### Bibliographie",
        "latex_report": "PDF erstellen",
        "development": "#### Entwicklung",
        "instantaneous": "Momentan",
        "envelope": "Hüllkurve",
        "reference_60hz": "Referenz 60 Hz",
        "current_label": "Strom:",
        "time_label": "Zeit [ms]",
        "current_axis_label": "Strom [pu]",
        "voltage_axis_label": "Spannung [pu]",
        "use_xelatex_compiler": "den xelatex-Compiler verwenden",
        "or": "order",
    }
}
